language: php
php:
  - 5.3.3
mysql:
  database: drupal
  username: root
  encoding: utf8
before_script:
  - find ~/.phpenv php-cgi
  - pyrus channel-discover pear.drush.org
  - pyrus install drush/drush
  - phpenv rehash
  - mkdir -p build
  - drush -v make drupal-sauce.make build/html
  - cd build/html
  - drush -v site-install standard --db-url=mysql://root:@localhost/drupal --yes
  - drush cc all
  - drush runserver 8080 &
  - cd -
  - composer install --prefer-source
script: bin/behat --profile=travis-ci
